### ISSUE TITLE
question about "Subcharacter radicals and components"

### ISSUE THREAD

**Issue by dyzhou2015** [HKUST-KnowComp/JWE#1]
hi, I have deploy the spider code on that Scrapy Cloud,  but it has 1 hour limited for free use. i wonder if it is convenient to provide the processed char2comp.txt and comp.txt which will be used for training , any help would be appreciated.thanks ahead.

**Comment by jinxing94** [comment]
I did not upload the crawled resource because of copyright concerns.  Could you provide your email address ? I could send the files to you.

**Comment by dyzhou2015** [comment]
Thanks a lot, My email address is dyzhou2015@outlook.com .

**Comment by xh-2016** [comment]
hello，i face the same problem，so i need the two file char2comp.txt and comp.txt，too. i wonder if you can seed me a copy？thanks a lot， xh20171212@163.com is my email address.thanks again~

**Comment by jinxing94** [comment]
Hi, I have sent you the resource, please check the email.

**Comment by yangqinj** [comment]
hello, I face the same problem. I actually cannot figure out how to deploy the spider code to Scrapy Cloud. Could you please send me the char2comp.txt and comp.txt files. My email is yangqinj@mail2.sysu.edu.cn. thanks a lot~

**Comment by gokunwu** [comment]
hello，i face the same problem，may i can get the two file char2comp.txt and comp.txt，too? thanks a lot! my email is wukunbupt@163.com

**Comment by jinxing94** [comment]
Hi, I have uploaded the subcharacter files for research convenience and added a copyright disclaimer about the data in reademe:).
