### ISSUE TITLE
about the data preprocessing

### ISSUE THREAD

**Issue by michael-wzhu** [HKUST-KnowComp/JWE#2]
Hi. It seems that the blog you referred to about pre-processing instructions of the Chinese wiki dump is no longer accessible. so could you provide some more details about pre-processing? or add a script to the repo? Many thx

**Comment by jinxing94** [comment]
Hi. You can download the text file after preprocessing at [oneline baidu box](https://pan.baidu.com/s/1jINyG6q)
As far as I can remember, the preprocessing steps include:
1.  Use [wiki extractor]( http://medialab.di.unipi.it/wiki/Wikipedia_Extractor) or python gensim.corpora to extract plain text from the xml file;
2. Remove non Chinese characters by using regular expression;
3. Use opencc to convert traditional Chinese to simplified Chinese;
4. Perform Chinese word segmentation by using [THULAC](http://thulac.thunlp.org) package.

**Comment by michael-wzhu** [comment]
Thanks for the quick reponse. very much appreciated. I wonder whether your group have tried training this embedding model on other corpus? and whether other larger corpus can help further improve the quality of the embeddings?

**Comment by jinxing94** [comment]
I did not try training this model on other corpus. 

[Sogou Lab](http://www.sogou.com/labs/resource/contact.php) publishes a large corpus, but the corpus is too big to download it. One needs to mail a hard drive to Sogou company to copy it.

I personally think larger corpus may help further improve the quality of the embeddings.
