### ISSUE TITLE
Final representation of words

### ISSUE THREAD

**Issue by Saltychtao** [HKUST-KnowComp/JWE#4]
Hi, I noticed that your final output of the word embedding, character embedding, and subcharacter embedding are separated. I am wondering that should I manually use the sum of all three types of embedding as the final representation of  the word, or just use the output word embedding ?

**Comment by jinxing94** [comment]
I just used the output word embeddings in the word similarity and word analogy experiments. You could try the sum of three types of embeddings for word similarity, word analogy, or downstream tasks.

**Comment by Saltychtao** [comment]
I got it, thanks a lot!
