### ISSUE TITLE
comp_vec

### ISSUE THREAD

**Issue by Rainysunnyday** [HKUST-KnowComp/JWE#5]
您好，我想请问一下，comp_vec是除偏旁部首之外的部分么？

**Comment by jinxing94** [comment]
不是，comp_vec包括偏旁部首。radicals指偏旁部首， component指汉字部件；汉子部件包括偏旁部首。

**Comment by Rainysunnyday** [comment]
也就是说component包括汉字的所有组成部件对吗？还有一个问题就是，case studies里是怎么按照component找出最接近的字词来的呢？

**Comment by jinxing94** [comment]
嗯，对。case studies是按照component的embedding向量和字、词的embedding向量的cosin相似度最大找出来的。

**Comment by Rainysunnyday** [comment]
噢噢，知道了，蟹蟹您~ 我还想问一下，您有没有pytorch版的实现代码呢~

**Comment by jinxing94** [comment]
没有。

**Comment by Rainysunnyday** [comment]
嗯嗯好的吧，谢谢~

**Comment by Rainysunnyday** [comment]
那请问您有case studies的代码不^^

**Comment by jinxing94** [comment]
找不到了，忘了保存这个了。

**Comment by Rainysunnyday** [comment]
嗯嗯好哒

**Comment by Crescentz** [comment]
> 噢噢，知道了，蟹蟹您~ 我还想问一下，您有没有pytorch版的实现代码呢~
请问你有pytorch代码分享么，或者找到其他人的

**Comment by Crescentz** [comment]
> 噢噢，知道了，蟹蟹您~ 我还想问一下，您有没有pytorch版的实现代码呢~

请问你有pytorch代码分享么，或者找到其他人的
