### ISSUE TITLE
How the three vectors are trained together

### ISSUE THREAD

**Issue by iriscxy** [HKUST-KnowComp/JWE#6]
In your code, I guess the only place where the three vectors have connections with each other is `syn1neg[c + l2] += g1 * neu1[c] + g2 * neuchar[c] + g3 * neucomp[c]`. I'm not familiar with gradient policy in C, so could you explain more about how these three vectors are trained together? Since we only use the output word_vec file, how do the char_vec and comp_vec help it gain better performance?

**Comment by jinxing94** [comment]
Although char_vec and comp_vec may be used in downstream tasks such as text classification, we indeed only use the output word_vec file for the evaluation of word representations in the paper.  

In our model, word, char, components all have input vector parameters,  while only word has output vector parameters (syn1neg in the code).   As you have noticed, the gradients  of the output word vector parameters are influenced by the tree components,  the gradients of input word vector are influenced in return by the output vector parameters during back propagation.  

See the code lines 573, 591 for updating output word vector parameters and code lines 567-569, 586-588, 603, 605 for updating input word vector parameters.

**Comment by Crescentz** [comment]
> In your code, I guess the only place where the three vectors have connections with each other is `syn1neg[c + l2] += g1 * neu1[c] + g2 * neuchar[c] + g3 * neucomp[c]`. I'm not familiar with gradient policy in C, so could you explain more about how these three vectors are trained together? Since we only use the output word_vec file, how do the char_vec and comp_vec help it gain better performance?

exceuse me,  any python version?
